USE [1];
GO
DROP PROCEDURE IF EXISTS GetCurrentUserPermissions
GO
CREATE PROCEDURE GetCurrentUserPermissions AS
BEGIN
	SELECT * FROM fn_my_permissions ((SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG='1'), 'OBJECT')
END
